"""Add MinioObjects

Revision ID: 292dc0e3a1a7
Revises: 01a9a30c663c
Create Date: 2026-01-09 03:24:38.422462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '292dc0e3a1a7'
down_revision: Union[str, Sequence[str], None] = '01a9a30c663c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minio_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('object_name', sa.String(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('etag', sa.String(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('minio_objects')
    # ### end Alembic commands ###
