"""add book page tables

Revision ID: 93882104e20c
Revises: 54a445f821e7
Create Date: 2026-01-13 02:11:57.358583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93882104e20c'
down_revision: Union[str, Sequence[str], None] = '54a445f821e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('minio_object_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['minio_object_id'], ['minio_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['file_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_comments_created_at'), 'file_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_file_comments_minio_object_id'), 'file_comments', ['minio_object_id'], unique=False)
    op.create_index('ix_file_comments_object_created', 'file_comments', ['minio_object_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_file_comments_parent_id'), 'file_comments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_file_comments_updated_at'), 'file_comments', ['updated_at'], unique=False)
    op.create_index(op.f('ix_file_comments_user_id'), 'file_comments', ['user_id'], unique=False)
    op.create_table('file_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('minio_object_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_like', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['minio_object_id'], ['minio_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('minio_object_id', 'user_id', name='uq_file_like_object_user')
    )
    op.create_index(op.f('ix_file_likes_created_at'), 'file_likes', ['created_at'], unique=False)
    op.create_index(op.f('ix_file_likes_minio_object_id'), 'file_likes', ['minio_object_id'], unique=False)
    op.create_index('ix_file_likes_object_user', 'file_likes', ['minio_object_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_file_likes_user_id'), 'file_likes', ['user_id'], unique=False)
    op.create_table('file_pages',
    sa.Column('minio_object_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['minio_object_id'], ['minio_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('minio_object_id')
    )
    op.create_index(op.f('ix_file_pages_created_at'), 'file_pages', ['created_at'], unique=False)
    op.create_index(op.f('ix_file_pages_updated_at'), 'file_pages', ['updated_at'], unique=False)
    op.create_table('comment_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_like', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['file_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', name='uq_comment_like_comment_user')
    )
    op.create_index(op.f('ix_comment_likes_comment_id'), 'comment_likes', ['comment_id'], unique=False)
    op.create_index('ix_comment_likes_comment_user', 'comment_likes', ['comment_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_comment_likes_created_at'), 'comment_likes', ['created_at'], unique=False)
    op.create_index(op.f('ix_comment_likes_user_id'), 'comment_likes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_likes_user_id'), table_name='comment_likes')
    op.drop_index(op.f('ix_comment_likes_created_at'), table_name='comment_likes')
    op.drop_index('ix_comment_likes_comment_user', table_name='comment_likes')
    op.drop_index(op.f('ix_comment_likes_comment_id'), table_name='comment_likes')
    op.drop_table('comment_likes')
    op.drop_index(op.f('ix_file_pages_updated_at'), table_name='file_pages')
    op.drop_index(op.f('ix_file_pages_created_at'), table_name='file_pages')
    op.drop_table('file_pages')
    op.drop_index(op.f('ix_file_likes_user_id'), table_name='file_likes')
    op.drop_index('ix_file_likes_object_user', table_name='file_likes')
    op.drop_index(op.f('ix_file_likes_minio_object_id'), table_name='file_likes')
    op.drop_index(op.f('ix_file_likes_created_at'), table_name='file_likes')
    op.drop_table('file_likes')
    op.drop_index(op.f('ix_file_comments_user_id'), table_name='file_comments')
    op.drop_index(op.f('ix_file_comments_updated_at'), table_name='file_comments')
    op.drop_index(op.f('ix_file_comments_parent_id'), table_name='file_comments')
    op.drop_index('ix_file_comments_object_created', table_name='file_comments')
    op.drop_index(op.f('ix_file_comments_minio_object_id'), table_name='file_comments')
    op.drop_index(op.f('ix_file_comments_created_at'), table_name='file_comments')
    op.drop_table('file_comments')
    # ### end Alembic commands ###
