services:
  backend:
    container_name: fastapi-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - db
      - minio
    ports:
      - "8000:8000"  
    volumes:
      - file_storage:/storage/files
      - logs:/storage/logs
    networks:
      - app_network

  frontend:
    container_name: frontend-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    - "5173:5173"
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - app_network

  nginx:
    container_name: nginx-proxy
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - file_storage:/storage/files
      - logs:/storage/logs
    networks:
      - app_network

  db:
    container_name: postgres-db
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  minio:
    container_name: minio-storage
    image: minio/minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - app_network

  minio_create_bucket:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - ./.env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      mc mb local/${MINIO_BUCKET_NAME} || true;
      mc anonymous set download local/${MINIO_BUCKET_NAME};
      exit 0;
      "
    networks:
      - app_network

  alembic:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: alembic-migrate
    env_file:
      - ./.env
    depends_on:
      - db
    command: ["alembic", "-c", "alembic.ini", "upgrade", "head"]
    networks:
      - app_network


networks:
  app_network:

volumes:
  pgdata:
  file_storage:
  logs:
  minio_data:
